- hosts: all
  become: yes
  become_user: root
  gather_facts: no
  tasks:
    - name: Install dependant packages
      vars:
        packages:
          - libxss1
          - libnss3
          - libsecret-1-0
      package:
        name: "{{packages}}"

    - name: Install Visual Studio Code
      block:
        - name: Check if package is already installed
          shell: dpkg --list | grep -E "^ii +code"
          ignore_errors: yes
          register: code_is_installed
        - name: Download and install Visual Studio Code if not present
          when: "code_is_installed.rc == 1"
          apt:
            deb: https://update.code.visualstudio.com/latest/linux-deb-x64/stable

    - name: Configure persistent storage
      block:
        - name: Create persistent storage directories
          with_items:
            - vscode
            - vscode/user_home
            - vscode/user_config
          file:
            path: "/mnt/persistent_storage/{{item}}"
            state: directory
            owner: dev
            group: dev

        - name: Map user home config directory to persistent storage
          file:
            dest: /home/dev/.vscode
            src: /mnt/persistent_storage/vscode/user_home
            state: link

        - name: Map user config directory to persistent storage
          file:
            dest: /home/dev/.config/Code
            src: /mnt/persistent_storage/vscode/user_config
            state: link
