- hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Download k3s install script
      get_url:
        dest: /home/vagrant/k3s-install.sh
        url: https://raw.githubusercontent.com/rancher/k3s/master/install.sh
        mode: +x

    - name: Execute install script
      shell: /home/vagrant/k3s-install.sh

    - name: Enable and start k3s service
      service:
        name: k3s
        enabled: yes
        state: started

    - name: Create aliases for standard k8s commands
      vars:
        accounts:
          - dev
          - vagrant
      block:
        - name: Create .k3s-aliases file
          with_items: "{{accounts}}"
          copy:
            dest: "/home/{{item}}/.k3s-aliases"
            src: k3s-aliases
            owner: "{{item}}"
            group: "{{item}}"
        - name: Add import to bash profile
          with_items: "{{accounts}}"
          lineinfile:
            path: "/home/{{item}}/.bashrc"
            line: 'source ~/.k3s-aliases'
